### ISSUE TITLE
Pizza Result Title Cutoff

### ISSUE THREAD

**Issue by doeiqts** [doeiqts/PizzaVoter#10]
If you vote for a "Hand Tossed White Garlic Parmesan" pizza it cuts off the title to "Hand Tossed White Garlic P..."

Should be fine just making it wrap.

**Comment by Stormsurfer36** [comment]
This is a feature...specifically I added css to add ... to cut it off.

**Comment by doeiqts** [comment]
If the information wasn't that important, then it'd be OK, but I'd like to know what sauce is being voted on without having to guess.

**Comment by doeiqts** [comment]
Fixed by #15
