### ISSUE TITLE
Make Mobile Wrapper Friendly

### ISSUE THREAD

**Issue by doeiqts** [doeiqts/PizzaVoter#26]
Some people were wanting the site to be more mobile wrapper friendly via stuff like

https://developer.chrome.com/multidevice/android/installtohomescreen

and 

https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

I'll see what I can do.

**Comment by shalander** [comment]
+1

**Comment by doeiqts** [comment]
Completed by #31
