### ISSUE TITLE
Fix Topping Bug

### ISSUE THREAD

**Issue by doeiqts** [doeiqts/PizzaVoter#9]
If you vote for a whole topping and then two half toppings (in the order, from top to bottom) then it doesn't save the last half topping on the page refresh. The topping that is missing from the user's 4 pizza votes _does_ make it into the vote list, but not the user's current votes form.

**Comment by Stormsurfer36** [comment]
To add to this: topping is persisted and appears in vote. Javascript function setPosition removes the final entry.

**Comment by doeiqts** [comment]
Fixed by #15
